version: '3'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-chatbot:1.0
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - WHATSAPP_PHONE_NUMBER=${WHATSAPP_PHONE_NUMBER}
    ports:
      - "5000:5000"
